#!/usr/bin/env python3
"""build_v2.py — render the V2 "browse" pages: a Netflix-style skin over the same content.

Same data as V1 (data/*.json), different presentation:
    V2/index.html      billboard + horizontal shelves (episodes, top callbacks, cast, the 1987 era,
                       politics, the real campuses) + method
    V2/ep01..ep10.html episode detail pages: backdrop, synopsis, callbacks as episode rows, the
                       politics and script panels (collapsed), next-episode card

Images
    assets/art/*.svg        generated by scripts/make_art.py — our own artwork, committed
    assets/img/commons/*    freely-licensed Commons photos with printed credits, committed
    IMDb CDN key art        HOTLINKED ONLY (never downloaded, never committed) with generated art
                            layered behind it as the fallback. Disable with --no-poster.

Usage:  python3 scripts/build_v2.py [--no-poster]
"""
from __future__ import annotations

import argparse
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "v2"
ART = "assets/art"          # written relative to the site root, prefixed in the page
ASSETS = "../assets"

sys.path.insert(0, str(ROOT / "scripts"))
from build_pages import load, e, SOURCES, SOURCE_LABELS, render_glossary  # noqa: E402

TAG_RED = '<span class="badge">'


def art(name: str) -> str:
    return f"{ASSETS}/art/{name}"


def src_line(keys: list[str]) -> str:
    out = []
    for k in keys:
        url = SOURCES.get(k)
        label = SOURCE_LABELS.get(k, k).split(":")[0]
        out.append(f'<a href="{e(url)}" rel="noopener">{e(label)}</a>' if url else e(label))
    return " · ".join(out)


def head(title: str, desc: str) -> str:
    return f"""<!doctype html>
<html lang="en" class="v2">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<meta name="color-scheme" content="dark">
<link rel="stylesheet" href="{ASSETS}/v2/netflix.css">
<link rel="icon" href="{art('logo.svg')}">
</head>
<body>
"""


def nav(back: str = "index.html") -> str:
    return f"""<header class="nf-nav">
  <a class="nf-logo" href="{e(back)}"><img src="{art('logo.svg')}" alt="">Origin Notes</a>
  <nav>
    <a href="index.html#episodes">Episodes</a>
    <a href="index.html#callbacks">Top callbacks</a>
    <a href="index.html#cast">Cast</a>
    <a href="index.html#original">The 1987 era</a>
    <a href="index.html#politics">Politics</a>
    <a href="index.html#campuses">Campuses</a>
  </nav>
  <div class="right">
    <button class="pill" data-action="toggle-spoilers" aria-pressed="false">Reveal spoilers</button>
    <a class="pill" href="../index.html">Text version (V1)</a>
  </div>
</header>
"""


FOOT = f"""<footer class="nf-foot">
  <p><b>Fan project. Not affiliated with Netflix, NBC or the rights holders.</b>
  Artwork on this page is generated by <code>scripts/make_art.py</code> (our own SVG). Campus photographs
  come from Wikimedia Commons under free licences and are credited individually. The show's key art is
  hotlinked from IMDb's CDN for identification only and is not redistributed with this site — turn it off
  with <code>python3 scripts/build_v2.py --no-poster</code>.</p>
  <p>Facts verified 2026-10-04 against Wikipedia's article on the 2026 series, Wikipedia's list of the
  original's episodes, and IMDb title IDs. Full method, tiers and sources: see the
  <a href="index.html#method">method section</a> or the <a href="../index.html">text version</a>.</p>
</footer>
<script src="{ASSETS}/v2/netflix.js" defer></script>
</body>
</html>
"""


def billboard(episodes, poster_url: str | None, counts: dict) -> str:
    poster = (f'<img class="poster" src="{e(poster_url)}" alt="Key art (hotlinked from IMDb)" '
              f'onerror="this.style.display=\'none\'" loading="lazy">') if poster_url else ""
    return f"""<section class="billboard">
  <div class="art"><img src="{art('hero.svg')}" alt=""></div>
  <div class="scrim"></div>
  {poster}
  <div class="copy">
    <p class="tag">A NETFLIX REVIVAL · ORIGIN NOTES</p>
    <h1>A Different World</h1>
    <div class="facts">
      <span class="badge-39">Premiered 24 Sep 2026 — 39 years to the day after 24 Sep 1987</span>
      <span>1 season</span><span>10 episodes</span><span>30–36m</span><span>Renewed for S2</span>
      <span>{sum(counts.values())} sourced callbacks</span>
    </div>
    <p class="syn">You binged the revival. This is the other end of every joke: the 1987–1993 episode each
    callback points back to, what it actually did, and why it still matters — one page per episode.</p>
    <div class="actions">
      <a class="btn" href="ep01.html">▶ Start with episode 1</a>
      <a class="btn ghost" href="index.html#callbacks">ⓘ Top callbacks</a>
      <a class="btn ghost" href="../index.html">Read the text version</a>
    </div>
  </div>
</section>
"""


def shelf(id_: str, title: str, hint: str, cards: list[str], more: str = "") -> str:
    if not cards:
        return ""
    more_html = f'<a class="more" href="{more}">Explore all →</a>' if more else ""
    return f"""<section class="shelf" id="{e(id_)}">
  <div class="shelf-head"><h2>{e(title)}</h2><span class="hint">{e(hint)}</span>{more_html}</div>
  <div class="rail">{''.join(cards)}</div>
</section>
"""


def episode_card(ep: dict, count: int) -> str:
    return f"""<a class="card" href="ep{ep['number']:02d}.html">
  <img class="still" src="{art(f"ep{ep['number']:02d}.svg")}" alt="Episode {ep['number']} artwork" loading="lazy">
  <div class="body">
    <div class="row1"><span class="num">EPISODE {ep['number']}</span></div>
    <h3>{e(ep['title'])}</h3>
    <p class="desc">{e(ep['hook'])}</p>
    <div class="tags"><span>{count} callbacks</span><span>dir. {e(ep['director'])}</span></div>
  </div>
</a>"""


def top_callback_cards(callbacks: dict, episodes_by_num: dict) -> list[str]:
    weight = {"title-echo": 6, "cast": 5, "lore": 4, "theme": 3, "reading": 2}
    conf = {"verified": 3, "likely": 2, "interpretation": 1}
    scored = sorted(
        callbacks["callbacks"],
        key=lambda c: -(weight.get(c["tier"], 0) + conf.get(c["confidence"], 0)),
    )
    picked, per_ep = [], {}
    for c in scored:
        if per_ep.get(c["episode"], 0) >= 2:
            continue
        picked.append(c)
        per_ep[c["episode"]] = per_ep.get(c["episode"], 0) + 1
        if len(picked) == 10:
            break
    cards = []
    for i, c in enumerate(picked, 1):
        ep = episodes_by_num[c["episode"]]
        o = c["origin"]
        cards.append(f"""<a class="card rank" href="ep{c['episode']:02d}.html#{e(c['id'])}">
  <img class="still" src="{art(f"ep{c['episode']:02d}.svg")}" alt="" loading="lazy">
  <span class="rankno">{i}</span>
  <div class="body">
    <div class="row1"><span class="num">EPISODE {c['episode']}</span>
      <span class="badge {e(c['confidence'])}">{e(c['confidence'])}</span>
      <span class="badge">{e(c['tier'])}</span></div>
    <h3>{e(c['scene_2026'][:78])}{'…' if len(c['scene_2026']) > 78 else ''}</h3>
    <p class="desc">from S{o['season']}·E{o['episode']} “{e(o['title'])}” ({e(o['air_date'])})</p>
  </div>
</a>""")
    return cards


def cast_cards(characters: dict, headshots: dict) -> list[str]:
    cards = []
    for group in ("main", "special_guest"):
        for p in characters.get(group, []):
            slug = re.sub(r"[^a-z0-9]+", "-", p["name_2026"].lower()).strip("-")
            shot = headshots.get(p["actor"])
            img = (f'<img src="{e(shot)}" alt="{e(p["actor"])}" loading="lazy" '
                   f'onerror="this.style.display=\'none\'">') if shot else ""
            returning = p.get("name_original")
            cards.append(f"""<a class="card cast" href="../index.html#who">
  <div style="position:relative">{img}
    <img src="{art(f'cast-{slug}.svg')}" alt="" style="position:{"absolute;inset:0" if img else "static"};z-index:{-1 if img else 0}">
  </div>
  <div class="body">
    <h3>{e(p['name_2026'])}</h3>
    <p class="desc">{e(p['actor'])}</p>
    <div class="tags">
      <span>{e(p['role_2026'])}</span>
      {f'<span>in 1987: {e(returning)}</span>' if returning else '<span>new character</span>'}
    </div>
  </div>
</a>""")
    return cards


def original_cards(starter: dict) -> list[str]:
    cards = []
    for i, s in enumerate(starter["episodes"], 1):
        illum = ", ".join(f"ep{n}" for n in s["illuminates"])
        cards.append(f"""<a class="card" href="../index.html#starter">
  <img class="still" src="{art(f'orig{i:02d}.svg')}" alt="" loading="lazy">
  <div class="body">
    <div class="row1"><span class="num">S{s['season']}·E{s['episode']}</span><span class="badge">{e(s['air_date'])}</span></div>
    <h3>{e(s['title'])}</h3>
    <p class="desc">{e(s['why'][:120])}{'…' if len(s['why']) > 120 else ''}</p>
    <div class="tags"><span>explains {e(illum)}</span><span>our pick</span></div>
  </div>
</a>""")
    return cards


def politics_cards(politics: dict) -> list[str]:
    cards = []
    for p in politics["episodes"]:
        cards.append(f"""<a class="card" href="ep{p['episode']:02d}.html#politics">
  <img class="still" src="{art('politics.svg')}" alt="" loading="lazy">
  <div class="body">
    <div class="row1"><span class="num">EPISODE {p['episode']}</span></div>
    <h3>{e(p['statement'][:96])}{'…' if len(p['statement']) > 96 else ''}</h3>
    <p class="desc">Collapsed section on the episode page: what the show is saying, what the original said
    first, and what is happening now — sourced.</p>
    <div class="tags"><span>{len(p['now'])} sourced context items</span></div>
  </div>
</a>""")
    return cards


def campus_cards() -> list[str]:
    credits_file = ROOT / "assets/img/commons/CREDITS.json"
    if not credits_file.exists():
        return []
    credits = json.loads(credits_file.read_text())["files"]
    cards = []
    for c in credits:
        rel = c["file"].replace("assets/", f"{ASSETS}/", 1)
        author = re.sub(r"\s+", " ", re.sub("<[^>]+>", "", c["author"]))[:70]
        cards.append(f"""<article class="card photo">
  <img src="{e(rel)}" alt="{e(c['subject'])}" loading="lazy">
  <div class="credit">
    <b>{e(c['subject'])}</b><br>
    Photo: {e(author)} · {e(c['license'])} · <a href="{e(c['page_url'])}" rel="noopener">Commons</a>
  </div>
  <div class="body">
    <p class="desc">Hillman is fictional. These are real campuses of the kind the original was built
    from — the show was inspired by student life at historically Black colleges and universities.</p>
  </div>
</article>""")
    return cards


def render_v2_index(episodes, callbacks, politics, characters, timeline, glossary, starter, headshots, poster) -> str:
    counts = {ep["number"]: len(ep["callbacks"]) for ep in episodes["episodes"]}
    by_num = {ep["number"]: ep for ep in episodes["episodes"]}
    tl = "".join(
        f'<li style="margin-bottom:.6rem"><b>{e(ev["date"])}</b> — {e(ev["label"])} '
        f'<span style="color:var(--fg-mute)">{e(ev["note"])[:160]}</span></li>'
        for ev in timeline["events"])
    tiers = "".join(f"<li><b>{e(k)}</b> — {e(v)}</li>" for k, v in callbacks["tiers"].items())
    confs = "".join(f"<li><b>{e(k)}</b> — {e(v)}</li>" for k, v in callbacks["confidence_levels"].items())

    return head("A Different World (2026) — Origin Notes · the Netflix-style browse",
                "Netflix-style browsing view of every 2026 callback and its 1987–1993 origin.") + nav() + f"""
{billboard(episodes, poster, counts)}
{shelf("episodes", "Episodes", "season 1 · all ten released 24 Sep 2026",
       [episode_card(ep, counts[ep["number"]]) for ep in episodes["episodes"]], "index.html#episodes")}
{shelf("callbacks", "Top callbacks this season", "ranked: title echoes and returning cast first",
       top_callback_cards(callbacks, by_num), "index.html#method")}
{shelf("cast", "Who's who — the bridge", "returning originals are badged",
       cast_cards(characters, headshots), "../index.html#who")}
{shelf("original", "The 1987–1993 era: watch these 12", "our pick, ordered by what they explain",
       original_cards(starter), "../index.html#starter")}
{shelf("politics", "Politics & the moment", "collapsed on each episode page",
       politics_cards(politics), "index.html#politics")}
{shelf("campuses", "The real campuses behind Hillman", "Wikimedia Commons, free licences, credited",
       campus_cards(), "index.html#campuses")}

<section class="meth" id="method">
  <h2>How this page is made, and what it refuses to do</h2>
  <p>{e(callbacks.get('method_note',''))}</p>
  <h3>Tiers</h3><ul>{tiers}</ul>
  <h3>Confidence</h3><ul>{confs}</ul>
  <h3>1984 → 2026</h3><ul style="list-style:none;padding:0">{tl}</ul>
  <h3>Glossary</h3><dl>{render_glossary(glossary)}</dl>
  <h3>Rebuild it</h3>
  <ul>
    <li><code>python3 scripts/make_art.py</code> — redraw all the artwork</li>
    <li><code>python3 scripts/fetch_commons.py</code> — re-download the credited campus photos</li>
    <li><code>python3 scripts/build_pages.py &amp;&amp; python3 scripts/build_v2.py</code> — rebuild V1 and V2</li>
    <li><code>python3 scripts/verify_pages.py &amp;&amp; python3 scripts/verify_v2.py</code> — the machine checks</li>
  </ul>
</section>
""" + FOOT


def render_v2_episode(ep, callbacks, politics, transcripts, candidates, episodes, headshots) -> str:
    cb_index = {c["id"]: c for c in callbacks["callbacks"]}
    cbs = [cb_index[cid] for cid in ep["callbacks"] if cid in cb_index]
    pol = next(p for p in politics["episodes"] if p["episode"] == ep["number"])
    next_ep = next((x for x in episodes["episodes"] if x["number"] == ep["number"] + 1), None)
    prev_ep = next((x for x in episodes["episodes"] if x["number"] == ep["number"] - 1), None)

    rows = []
    for i, c in enumerate(cbs, 1):
        o = c["origin"]
        spoiler = " spoiler" if c.get("spoiler") else ""
        rows.append(f"""<div class="ep-row" id="{e(c['id'])}" data-callback="{e(c['id'])}" data-tier="{e(c['tier'])}">
  <div class="n">{i}</div>
  <img class="thumb" src="{art(f"ep{ep['number']:02d}.svg")}" alt="" loading="lazy">
  <div>
    <h3>{e(c['scene_2026'])}</h3>
    <p class="src{spoiler}"><b>S{o['season']}·E{o['episode']} — “{e(o['title'])}”</b> · first aired {e(o['air_date'])}<br>{e(o['what_happened'])}</p>
    <p class="why">{e(o['why_it_matters_now'])}</p>
    <p class="srcline">Sources: {src_line(c['sources'])} · search terms: <code>{e(' '.join(c.get('scene_search', [])))}</code></p>
  </div>
  <div class="badges">
    <span class="badge">{e(c['tier'])}</span>
    <span class="badge {e(c['confidence'])}">{e(c['confidence'])}</span>
    <span class="dur">{'spoilers' if c.get('spoiler') else 'safe'}</span>
  </div>
</div>""")

    # politics panel
    ctx = {x["id"]: x for x in politics["context"]}
    now = []
    for item in pol["now"]:
        c = ctx.get(item.get("context")) if item.get("context") else None
        if c:
            now.append(f'<li>{e(item["note"])} <span style="color:var(--fg-mute)">Source: '
                       f'<a href="{e(c["source"])}" rel="noopener">context “{e(c["id"])}”</a>, {e(c["retrieved"])}</span></li>')
        else:
            now.append(f'<li>{e(item["note"])} <span style="color:var(--fg-mute)">No source attached — flagged, not asserted.</span></li>')
    pr = pol["precedent"]
    politics_panel = f"""<details class="nf" id="politics">
  <summary>Politics &amp; the moment<span class="hint">the show's statements, and the original's</span></summary>
  <div class="inner">
    <span class="tagline">What the episode is about</span><p>{e(pol['statement'])}</p>
    <span class="tagline">The original said it first — S{pr['season']}·E{pr['episode']} “{e(pr['title'])}” ({e(pr['air_date'])})</span>
    <p>{e(pr['what'])}</p>
    <span class="tagline">What is happening now</span><ul>{''.join(now)}</ul>
    <span class="tagline">Our reading — interpretation, not fact</span><p class="reading">{e(pol['reading'])}</p>
  </div>
</details>"""

    # script panel
    tr = transcripts.get(ep["number"])
    cands = candidates.get(ep["number"], [])
    cand_html = ""
    if cands:
        items = []
        for cand in cands:
            for scene in cand.get("scenes", [])[:6]:
                items.append(f'<li><code>{e(scene["start"])}–{e(scene["end"])}</code> <b>{e(cand["topic_label"])}</b> — '
                             f'{e(", ".join(scene["terms"][:5]))} <span style="color:var(--fg-mute)">(score {scene["score"]})</span></li>')
        if items:
            cand_html = ('<span class="tagline">Scene candidates the scanner found</span>'
                         '<p style="color:var(--fg-mute);font-size:.86rem">Output of '
                         '<code>scripts/find_scenes.py</code> over the imported transcript.</p><ul>' + "".join(items) + "</ul>")
    if tr:
        cues = "".join(f'<div class="cue"><span class="tc">{e(c["start"])}</span>'
                       f'<span class="cue-text">{e(c["plain"])}</span></div>' for c in tr["cues"])
        body = (f'<div class="ts-search"><input id="ts-search" type="search" placeholder="Search this transcript…">'
                f'<span class="badge" id="ts-count">{len(tr["cues"])} lines</span></div>'
                f'<div class="transcript">{cues}</div>')
        hint = f'{tr["cue_count"]} lines · {tr["duration"]}'
    else:
        hint = "no transcript imported yet"
        body = ('<div class="notice"><b>Transcript not imported.</b> The panel is wired and waiting. '
                "Netflix subtitle text is copyrighted, so we publish only short attributed excerpts — but you can "
                "make the full text readable locally (or decide to publish it) by dropping the episode's subtitle "
                'file into <code>subtitles/</code> and running <code>python3 scripts/import_subtitles.py</code>. '
                'Accepted: <code>.srt</code>, <code>.vtt</code>, Netflix <code>.ttml</code>/<code>.dfxp</code>, '
                'or a <code>.json</code> export from the Netflix Subtitle Translator userscript cache.</div>')
    script_panel = f"""<details class="nf" id="script">
  <summary>Full script<span class="hint">{e(hint)}</span></summary>
  <div class="inner">
    <p style="color:var(--fg-mute);font-size:.86rem">Collapsed by default, at the bottom. Kept local — never published wholesale.</p>
    {cand_html}{body}
  </div>
</details>"""

    more_cards = ""
    others = [x for x in episodes["episodes"] if x["number"] != ep["number"]][:6]
    if others:
        more_cards = shelf("more", "More episodes", "the rest of season 1",
                           [episode_card(o, len(o["callbacks"])) for o in others])

    nxt = ""
    if next_ep:
        nxt = f"""<a class="next-ep" href="ep{next_ep['number']:02d}.html">
  <img src="{art(f"ep{next_ep['number']:02d}.svg")}" alt="">
  <div><h3>Next episode · {next_ep['number']}. {e(next_ep['title'])}</h3>
  <p>{e(next_ep['hook'])}</p></div>
</a>"""
    back_link = "index.html" if not prev_ep else f"ep{prev_ep['number']:02d}.html"
    return head(f"Episode {ep['number']}: {ep['title']} — A Different World Origin Notes",
                ep["hook"]) + nav(back_link) + f"""
<section class="detail-hero">
  <img src="{art(f"ep{ep['number']:02d}.svg")}" alt="">
  <div class="scrim"></div>
  <div class="copy">
    <p class="tag">EPISODE {ep['number']} OF 10 · RELEASED {e(ep['released'])}</p>
    <h1>{e(ep['title'])}</h1>
    <div class="meta">
      <span>{len(cbs)} documented callbacks</span>
      <span>Directed by {e(ep['director'])}</span>
      <span>Written by {e(ep['writer'])}</span>
      <span class="badge-39">39 years after the original premiere</span>
    </div>
    <p>{e(ep['beat'])}</p>
    <div class="actions">
      <a class="btn" href="#callbacks">▶ The callbacks</a>
      <a class="btn ghost" href="#politics">Politics &amp; the moment</a>
      <a class="btn ghost" href="#script">Full script</a>
      {f'<a class="btn ghost" href="ep{prev_ep["number"]:02d}.html">← Episode {prev_ep["number"]}</a>' if prev_ep else ''}
    </div>
  </div>
</section>

<section class="episodes-list" id="callbacks">
  <div class="shelf-head" style="padding-left:0"><h2>Callbacks in this episode</h2>
    <span class="hint">what you saw → the original episode → why it matters</span>
    <button class="pill" data-action="expand-all" data-state="closed" style="margin-left:auto">Expand all</button>
  </div>
  {''.join(rows)}
</section>

<section class="panel-wrap">{politics_panel}{script_panel}</section>
{nxt}
{more_cards}
""" + FOOT


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-poster", action="store_true", help="do not hotlink IMDb key art")
    args = ap.parse_args()

    episodes = load("episodes.json")
    callbacks = load("callbacks.json")
    politics = load("politics.json")
    characters = load("characters.json")
    timeline = load("timeline.json")
    glossary = load("glossary.json")
    starter = load("starter-path.json")
    assert episodes and callbacks and politics and characters and timeline and glossary and starter, \
        "all data files are required and must load"

    # headshots and key art are derived from the probe, never hand-copied
    headshots, poster = {}, None
    probe = ROOT / "research/raw/image_sources.json"
    if probe.exists():
        d = json.loads(probe.read_text())
        for term, hits in d.get("imdb", {}).items():
            if hits and hits[0].get("image"):
                if hits[0]["id"] in ("tt33081352", "tt0092339"):
                    continue
                headshots[term] = hits[0]["image"]
        key_art = d.get("imdb", {}).get("tt33081352") or []
        if key_art and key_art[0].get("image") and not args.no_poster:
            poster = key_art[0]["image"]

    transcripts, candidates = {}, {}
    for n in range(1, 11):
        f = DATA / "scripts" / f"ep{n:02d}.json"
        if f.exists():
            transcripts[n] = json.loads(f.read_text())
    cdir = DATA / "candidates"
    if cdir.exists():
        for f in sorted(cdir.glob("ep*-*.json")):
            m = re.match(r"ep(\d+)-", f.name)
            if m:
                candidates.setdefault(int(m.group(1)), []).append(json.loads(f.read_text()))

    OUT.mkdir(exist_ok=True)
    (OUT / "index.html").write_text(
        render_v2_index(episodes, callbacks, politics, characters, timeline, glossary, starter, headshots, poster))
    for ep in episodes["episodes"]:
        (OUT / ep["page"]).write_text(
            render_v2_episode(ep, callbacks, politics, transcripts, candidates, episodes, headshots))

    print(f"built v2/index.html + {len(episodes['episodes'])} episode pages")
    print(f"  poster hotlink: {'on (' + poster[:60] + '…)' if poster else 'off'}")
    print(f"  cast headshots hotlinked: {len(headshots)}")
    print(f"  transcripts: {sorted(transcripts) or 'none'}  ·  campus photos: "
          f"{len(campus_cards())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
